/* Generated by           cobc 2.2.0 */
/* Generated from         main.cob */
/* Generated at           Jun 12 2021 15:49:20 */
/* GnuCOBOL build date    Jul 17 2018 20:29:40 */
/* GnuCOBOL package date  Sep 06 2017 18:48:43 UTC */
/* Compile command        cobc -C main.cob */

/* Program local variables for 'MAIN' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_6[30] __attribute__((aligned));	/* UserName */
static cob_u8_t	b_7[1] __attribute__((aligned));	/* Num1 */
static cob_u8_t	b_8[1] __attribute__((aligned));	/* Num2 */
static cob_u8_t	b_9[2] __attribute__((aligned));	/* Total */
static cob_u8_t	b_10[9] __attribute__((aligned));	/* SSNum */

/* End of data storage */


/* Fields */
static cob_field f_6	= {30, b_6, &a_2};	/* UserName */

/* End of fields */

