/* Generated by           cobc 2.2.0 */
/* Generated from         main.cob */
/* Generated at           Jun 12 2021 15:49:20 */
/* GnuCOBOL build date    Jul 17 2018 20:29:40 */
/* GnuCOBOL package date  Sep 06 2017 18:48:43 UTC */
/* Compile command        cobc -C main.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x21,   0,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {18, (cob_u8_ptr)"What is your Name ", &a_1};
static const cob_field c_2	= {6, (cob_u8_ptr)"hello ", &a_1};

	/* Decimal constants */
